name: DTT-00AK2

on:
  push:
    branches:
      - master

jobs:
  installing-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache de módulos do Node.js
        uses: actions/cache@v2
        with:
          path: DTT-00AK2_dependencies
          key: ${{ runner.os }}-${{ hashFiles('**/apt.lock')}}

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Clonar repositório Aircrack-ng
        run: git clone https://github.com/aircrack-ng/aircrack-ng

      - name: Compilar e Instalar o Aircrack-ng
        run: |
          cd aircrack-ng
          autoreconf -i
          ./configure --with-experimental
          make
          sudo make install
          sudo ldconfig
